### ISSUE TITLE
v4.0 Checklist

### ISSUE THREAD

**Issue by lhz516** [lhz516/react-h5-audio-player#233]
- [ ] Update bundling tool from Webpack to Vite
- [ ] Update Storybook to the latest version and use Vite as well.
- [ ] Update testing lib from Enzyme to React Testing Library
- [ ] Reactor the code to use React hooks instead of class components
- [ ] Use CSS variables for better overwrite experience
- [ ] Drop IE11 support
- [ ] Drop React 16 support
- [ ] Remove the APIs that have deprecation warnings in 3.x

Please post your feedbacks/suggestions/concerns here if any.

**Comment by lhz516** [comment]
published 4.0.0-beta.0

Release notes: https://www.npmjs.com/package/react-h5-audio-player/v/4.0.0-beta.0

feel free to try it out and report any issues here.
