### ISSUE TITLE
V3 Roadmap

### ISSUE THREAD

**Issue by lhz516** [lhz516/react-h5-audio-player#27]
The audio player V3 will mainly solve some historical issues and introduce a flexible layout feature.

- [x] Drop support under React 16.3.0 so that `createRef` API and some new lifecycles can be used
- [x] Drop support of IE10 since it had stopped being maintained by Microsoft after 1/14/2020
- [x] `onListen`'s argument will be changed from current time number to Event object
  - You can still get current time by `event.target.currentTime`
- [x] Ultra flexible layout (Props name TBD)
  - custom action buttons which are sortable with built-in buttons

The default view of V3 will be exactly the same as V2. If you are already using React 16.3.0+, you almost don't need to migrate anything unless you used `onListen` props.

Feel free to give any suggestions.
